server:
  port: 8080

spring:
  application:
    name: AiDaily
  datasource:
    url: jdbc:mysql://120.76.206.153:3306/ai_daily?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: admin
    password: ymumwKotcoq(
    driver-class-name: com.mysql.cj.jdbc.Driver

ai:
  enabled: true
  provider: deepseek
  deepseek:
    api-key: sk-dec846b48cb344bd9779b32686372a37
    base-url: https://api.deepseek.com
    model: deepseek-chat
    timeout-ms: 60000

feishu:
  app-id: cli_a0deb7329178500d
  app-secret: X4FOvLzytEyJF9q4n3gOIbFntEm31k0e
  verification-token: 6Kx7XH3d2yHb22ZlYagZIg0zTcGBNH3a
  encrypt-key: vdfq3axRjMZDqGTIPXr8Ab6s6qGkghoP

logging:
  level:
    com.aidaily: INFO
